### PR TITLE
config: extended default mime blacklist

### PR DESCRIPTION
**Pull request by jstucke**

### CODE REVIEW

**Comment by maringuu** [comment]
Can you sort the list? 
Also, can you make the list span over multiple lines? I find it hard to comprehend.

**Comment by jstucke** [comment]
> Also, can you make the list span over multiple lines? I find it hard to comprehend.

Since the config still uses the rather restricted ini format, this is not possible (without resorting to backslashes). But it is if we convert the config to toml. I took a look at all the places where the config is used and since it looked manageable, I created a PR: https://github.com/fkie-cad/fact_extractor/pull/152

**Comment by maringuu** [comment]
Please note, that the ini format that python implements supports multiline values.
https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

**Comment by jstucke** [comment]
> Please note, that the ini format that python implements supports multiline values. https://docs.python.org/3/library/configparser.html#supported-ini-file-structure

Yes, technically, but do we really want that?
grafik

TOML is designed to be unambiguous and comes with native support for complex data structures. That is why we switched to it in FACT_core (also we can use pydantic for better validation)

**Comment by jstucke** [comment]
But since it _does_ work, I changed it like you suggested. We can discuss switching to TOML in the other PR independent of the changes to the blacklist

**Review by maringuu — APPROVED** [review]

**Pull request merged**
