### PR TITLE
rebase Dockerfile

### PR DESCRIPTION
**Pull request by ElDavoo**
Rebase extractor to use baseimage 1.0.2 , nothing important changes

### CODE REVIEW

**Comment by dorpvom** [comment]
Hi Davide,
first let me thank you for your contributions. We'll fix our CI pipeline in the coming days after failing to allocated the appropriate time over easter break. Please have a bit more patience!

**Comment by jstucke** [comment]
For the record: The CI fail was caused by a [bug in pytest](https://github.com/pytest-dev/pytest/issues/12065) which is already fixed. There is no new release yet, though.

**Review by jstucke — APPROVED** [review]
LGTM

**Comment by jstucke** [comment]
#132 fixes the CI issues, so if you merge the changes into your branch the build should succeed.

**Comment by ElDavoo** [comment]
Done, and also rebased to 1.0.3

**Pull request merged**
