### PR TITLE
update Dockerfile to focal

### PR DESCRIPTION
**Pull request by wideglide**
use the `phusion/baseimage:focal-1.1.0` and update openjdk to v16

Is there any reason not to update the published docker image?

### CODE REVIEW

**Comment by jstucke** [comment]
Hi, thank you for your contribution! 

> Is there any reason not to update the published docker image?

Not really. The only problem is: Since the changes to Docker Hub, the image is no longer built automatically. We still need a workaround for that.

**Comment by wideglide** [comment]
Can you build on GitHub and push? 
https://github.com/marketplace/actions/build-and-push-docker-images

Or is it that you need to pay to host on Docker Hub now?

**Comment by wideglide** [comment]
for reference I built this docker image one the [release](https://github.com/wideglide/fact_extractor/blob/release/.github/workflows/builder.yml) branch and pushed to a personal [repository](https://hub.docker.com/repository/docker/wideglide/fact_extractor) on Docker Hub.

**Comment by jstucke** [comment]
It should work with a GitHub action, because pushing the images yourself still works (only building on Docker Hub doesn't work without an upgraded license). I will look into this. 

On the topic of the PR: I could not get the newly built image to work yet, but this seems to be due to unrelated problems that occurred in the meantime (e.g. https://github.com/fkie-cad/fact_extractor/issues/90). We will try to fix the issues first in order to make sure everything works.

**Comment by dorpvom** [comment]
Hi :wave:  PR #91 fixed the unrelated issues concerning our binwalk integration. Can you merge our current master into your fork so that we can verify that everything's fine using our CI? Thanks for the Contribution!

**Comment by wideglide** [comment]
I also had an issue with cstruct when I ran the tests.  In `install.py` cstruct is pinned to `v1.8`, but then when `jefferson-3` is installed, I believe it updates cstruct as it is a dependency (unpinned) for `jefferson-3`. I opened an PR (https://github.com/sviehb/jefferson/pull/34), but I'm not sure how responsive the maintainers are.

**Comment by wideglide** [comment]
closes #85

**Pull request merged**
