### PR TITLE
unpacker: add FIT image support

### PR DESCRIPTION
**Pull request by andrewjlamarche**
Support unpacking FIT images. 

Depends:
- https://github.com/fkie-cad/fact_helper_file/pull/37

Solves:
- https://github.com/fkie-cad/fact_extractor/issues/158

Notes:
- The included `fit.itb` is a FIT image containing a mock rootfs, kernel and device tree. The rootfs and kernel were generated with `/dev/urandom` as the input, and the device tree just has a description. Please feel free to check (there is no xz-like backdoor here with binary blobs).

### CODE REVIEW

**Comment by andrewjlamarche** [comment]
Ready for review, ping @jstucke 👍

**Comment by jstucke** [comment]
> Ready for review, ping @jstucke 👍

For whatever reason the CI does not want to run on this PR. Could you try to run `pre-commit` locally on the related files?

**Review by jstucke — APPROVED** [review]
Code looks good to me. Also I tested it with some samples from firmware images and can confirm that it works. Again thank you for your contribution!

**Comment by andrewjlamarche** [comment]
Cheers!

**Pull request merged**
